defaultPlatforms:
  - linux/arm64
  - linux/amd64

env:
  - CGO_ENABLED=0

flags:
  - -v

ldflags:
  - -s
  - -w

images:
  webhook:
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
  webhook-debug:
    dockerfile: Dockerfile
    target: debug
    platforms:
      - linux/amd64
      - linux/arm64
